### PR TITLE
use notifications mailing list for issues and PRs

### PR DESCRIPTION
**Pull request by pjfanning**
https://lists.apache.org/thread/jrqjdshp9vll8o75drdrynzk4b670vtn

### CODE REVIEW

**Comment by spangaer** [comment]
Given your own remark on discussions as user forum only in #24, I'd say discussions need to go there to.

But also to stop Git related notifications from flooding dev.

It's doubles from what get from GitHub anyway.

**Comment by pjfanning** [comment]
@spangaer I made the change you requested

**Review by jlprat — APPROVED** [review]
LGTM! Thanks @pjfanning

**Review by mdedetrich — APPROVED** [review]
LGTM

**Pull request merged**
