### PR TITLE
chore: Fix GraphApply.scala.template

### PR DESCRIPTION
**Pull request by He-Pin**
refs: https://github.com/apache/incubator-pekko/issues/875

I checked it locally, it works now.

image

### CODE REVIEW

**Review by jxnu-liguobin — COMMENTED** [review]
lgtm

**Review by jxnu-liguobin — APPROVED** [review]

**Comment by pjfanning** [comment]
Thanks @He-Pin - would it be possible to backport this to 1.0.x branch?

**Comment by He-Pin** [comment]
@pjfanning OK, does there are some backport github action can do this too?

**Comment by pjfanning** [comment]
> @pjfanning OK, does there are some backport github action can do this too?

I don't know of any automated way to do this.

**Comment by He-Pin** [comment]
Seem dotty is doing this.

**Pull request merged**
