### PR TITLE
[DRAFT] set Apache name in Pekko poms

### PR DESCRIPTION
**Pull request by pjfanning**
for https://github.com/apache/incubator-pekko/issues/1006

I'll generate more draft PRs but the build has been pretty brittle when I've tried changes.

changes were suggested by @laglangyue 

Due to the build brittleness, I want to try getting things working in 1 or 2 repos first before centralising a stable solution in sbt-pekko-build.

### CODE REVIEW

**Comment by mdedetrich** [comment]
> Due to the build brittleness, I want to try getting things working in 1 or 2 repos first before centralising a stable solution in sbt-pekko-build.

The place to put this is actually [sbt-apache-sonatype](https://github.com/mdedetrich/sbt-apache-sonatype), its whole purpose is to [setup the POM/artifacts for Apache projects](https://github.com/mdedetrich/sbt-apache-sonatype/blob/main/src/main/scala/org/mdedetrich/apache/sonatype/ApacheSonatypePlugin.scala#L57-L118) and using the `Apache` prefix in the POM like this is nothing unique to Pekko

**Comment by mdedetrich** [comment]
PR for sbt-pekko-build made at https://github.com/pjfanning/sbt-pekko-build/pull/7 . When I add the necessary functionality to sbt-apache-sonatype, I can just publish a new version of sbt-apache-sonatype and then we can re-release sbt-pekko-build with the new version and everything will just work.

**Comment by He-Pin** [comment]
is there a demo of the result `pom.xml`?

**Comment by mdedetrich** [comment]
> is there a demo of the result `pom.xml`?

There is a test for it https://github.com/mdedetrich/sbt-apache-sonatype/pull/31/files#diff-899556541f4c8f24264ebd0aa1e206513b1ba60ece3704900107968ef9fe5667R9-R13

**Comment by mdedetrich** [comment]
@pjfanning I think this can be closed, no?

**Pull request closed without merging**
