### PR TITLE
workaround-removal-biased-locking

### PR DESCRIPTION
**Pull request by pjfanning**
In JDK 20, JVM option `-XX:-UseBiasedLocking` fails the build.

Seems like a flag we can just remove from the sbtopts file.

### CODE REVIEW

**Comment by pjfanning** [comment]
@raboof @jrudolph @mdedetrich any objection to just removing `-XX:-UseBiasedLocking` from the sbtopt file?

**Comment by raboof** [comment]
No objection

**Comment by jrudolph** [comment]
Yep, just drop it, probably premature optimization anyway...

**Comment by mdedetrich** [comment]
All for it as well, in fact in general I wanted to remove the more esoteric JVM options (`-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler` is another one I would like to remove, I have seen it in other Pekko projects and while it may provide improvements to compile speed I have noticed on many occasions it also throws spurious exceptions/warnings).

**Pull request merged**
