### PR TITLE
Update to SBT 1.9.6 and use Apache Staging repo constant

### PR DESCRIPTION
**Pull request by mdedetrich**
SBT 1.9.5. added the `Resolver.ApacheMavenStagingRepo` constant

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
lgtm
```
[info] compiling 189 Scala sources and 3 Java sources to /home/runner/work/incubator-pekko/incubator-pekko/stream/target/scala-2.12/classes ...
[error] /home/runner/work/incubator-pekko/incubator-pekko/stream/src/main/scala/org/apache/pekko/stream/impl/io/compression/GzipDecompressor.scala:29:52: Generated class org.apache.pekko.stream.impl.io.compression.createLogic$$anon differs only in case from org.apache.pekko.stream.impl.io.compression.createLogic$$anon (defined in DeflateDecompressor.scala).
[error]   Such classes will overwrite one another on case-insensitive filesystems.
[error]   override def createLogic(attr: Attributes) = new DecompressorParsingLogic {
[error]                                                    ^
[error] /home/runner/work/incubator-pekko/incubator-pekko/stream/src/main/scala/org/apache/pekko/stream/impl/io/compression/GzipDecompressor.scala:40:26: Generated class org.apache.pekko.stream.impl.io.compression.createLogic$$anon$inflating$ differs only in case from org.apache.pekko.stream.impl.io.compression.createLogic$$anon$inflating$ (defined in DeflateDecompressor.scala).
[error]   Such classes will overwrite one another on case-insensitive filesystems.
[error]     override case object inflating extends Inflate(false) with Step
[error]                          ^
[error] two errors found
```

**Comment by mdedetrich** [comment]
@He-Pin I just noticed the error, I don't think this PR is causing it did someone forget to update mima filters or something?

**Comment by pjfanning** [comment]
> @He-Pin I just noticed the error, I don't think this PR is causing it did someone forget to update mima filters or something?

The CI job fails before even doing the mima check. There must be at least a chance that sbt 1.9.5 and something that it brings in (eg an upgraded copy of Zinc) are leading to this. It could be a real issue that has been hidden before but it could just be a bug in the compiler.

**Comment by mdedetrich** [comment]
> > @He-Pin I just noticed the error, I don't think this PR is causing it did someone forget to update mima filters or something?
> 
> The CI job fails before even doing the mima check. There must be at least a chance that sbt 1.9.5 and something that it brings in (eg an upgraded copy of Zinc) are leading to this. It could be a real issue that has been hidden before but it could just be a bug in the compiler.

SBT 1.9.5 did update zinc along with a new compiler bridge for Scala 2.13.x. Ill bring this upstream

**Comment by mdedetrich** [comment]
@sethtisue @eed3si9n  @lrytz  I am not sure if this is an issue with zinc, sbt or scala 2 compiler itself (with the update to the new compiler bridge)

Asking because I need to know where to report this.

**Comment by SethTisue** [comment]
The location of the root cause isn't obvious to me. I would say start in https://github.com/sbt/sbt/issues and we'll figure it out from there.

I'll run the sbt 1.9.5 upgrade through the Scala 2 community build and see if anything breaks.

**Comment by He-Pin** [comment]
@mdedetrich Update to 1.9.6~

**Comment by mdedetrich** [comment]
On it

**Review by pjfanning — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
Lgtm

**Comment by mdedetrich** [comment]
Everythings looking good, merging now

**Pull request merged**
