### PR TITLE
2024 added to copyright

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Review by samueleresca — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
Lgtm

**Comment by He-Pin** [comment]
Should we regenerate all the headers？

**Comment by pjfanning** [comment]
> Should we regenerate all the headers？

We don't have the year in many places. I didn't find anything else that needed updating.

**Pull request merged**
