### PR TITLE
Update sbt-apache-sonatype

### PR DESCRIPTION
**Pull request by mdedetrich**
Updates sbt-apache-sonatype which brings in https://github.com/mdedetrich/sbt-apache-sonatype/pull/15

References: https://github.com/apache/incubator-pekko/issues/328

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
> If there is no obvious way to fix the -javadoc jar issue, we can bring it to Incubator PMC or Legal and see what they say.

I deliberately left out `-javadoc` separately because some projects (i.e. Apache Daffodil) do not contain these files in generated documentation where as every single Apache project I could reference had it in `-sources`.

If its an issue its shouldn't be a problem for me to add it.

**Comment by pjfanning** [comment]
Some projects do seem to add license/notice to all jars - even javadoc jars. 

I think the path of least resistance is to fix up the javadoc jars too.

Otherwise, we're probably going to have to get into a debate with Incubator PMC and/or Legal.

@Claudenw wdyt?

**Comment by mdedetrich** [comment]
> Some projects do seem to add license/notice to all jars - even javadoc jars.

I know, but the `META-INF` folder doesn't even seem to be standard (in the general sense) for `-javadoc`, at least when packaging `-javadoc` locally.

**Comment by mdedetrich** [comment]
Hmm, some tests fail but I will re-run PR just to be safe

**Pull request merged**
