### PR TITLE
Rename verifyCodeStyle to checkCodeStyle

### PR DESCRIPTION
**Pull request by mdedetrich**
See https://github.com/apache/incubator-pekko-connectors/pull/208#discussion_r1294331081 for context

@He-Pin

### CODE REVIEW

**Comment by He-Pin** [comment]
@mdedetrich Will this confuse someone who contributes to both project(pekko & akka), like @dongxuwang

**Comment by mdedetrich** [comment]
> @mdedetrich Will this confuse someone who contributes to both projects(pekko & akka), like @dongxuwang

For me having the commands be consistent amongst pekko projects is more important then being in sync with akka. I can make a command alias from `verifyCodeStyle` to `checkCodeStyle` but I think this is a fairly minor problem.

@pjfanning wdyt?

**Review by He-Pin — APPROVED** [review]
lgtm, but better with anoter one lgtm?

**Comment by mdedetrich** [comment]
> lgtm, but better with anoter one lgtm?

Sure this is not urgent

**Review by gmethvin — APPROVED** [review]

**Comment by He-Pin** [comment]
@mdedetrich Now we have two lgtm, let me merge this then.

**Pull request merged**
