### PR TITLE
rename akka-docs dir to docs

### PR DESCRIPTION
**Pull request by pjfanning**
rename akka-docs dir to docs

### CODE REVIEW

**Comment by mdedetrich** [comment]
Ill check this either today or tomorrow

**Comment by mdedetrich** [comment]
@pjfanning Not sure if this is a bit munch but since we are renaming the sbt project/directory right now should we just change it to `docs` rather than `pekko-docs`? Every other pekko module just uses `docs` and its also the default directory for paradox (I believe calling it `akka-docs` initially was an oversight).

**Comment by pjfanning** [comment]
> @pjfanning Not sure if this is a bit munch but since we are renaming the sbt project/directory right now should we just change it to `docs` rather than `pekko-docs`? Every other pekko module just uses `docs` and its also the default directory for paradox (I believe calling it `akka-docs` initially was an oversight).



> @pjfanning Not sure if this is a bit munch but since we are renaming the sbt project/directory right now should we just change it to `docs` rather than `pekko-docs`? Every other pekko module just uses `docs` and its also the default directory for paradox (I believe calling it `akka-docs` initially was an oversight).

renamed to 'docs' instead

**Review by mdedetrich — APPROVED** [review]
Checked out the branch locally, also ran `docs/paradoxMarkdownToHtml` to make sure everything looks okay, good work lgtm.

**Review by gmethvin — APPROVED** [review]
LGTM

**Pull request merged**
