### PR TITLE
use temurin jdk in nightly-builds-latest-jdks.yml

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
looks like Temurin 21 is delayed - https://adoptium.net/en-GB/blog/2023/09/temurin21-delay/

**Comment by pjfanning** [comment]
may be released soon - https://github.com/adoptium/temurin/issues/8

**Comment by pjfanning** [comment]
@mdedetrich Adoptium have released the jdk 21 kits. I have tested this in another build. Are you happy for me to merge this?

**Comment by mdedetrich** [comment]
> @mdedetrich Adoptium have released the jdk 21 kits. I have tested this in another build. Are you happy for me to merge this?

Sure go ahead

**Comment by mdedetrich** [comment]
> @mdedetrich Adoptium have released the jdk 21 kits. I have tested this in another build. Are you happy for me to merge this?

Yes go ahead

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
just released :https://adoptium.net/zh-CN/temurin/releases/?version=21

**Pull request merged**
