### PR TITLE
chore: Update Scala version to 2.13.13 & 2.12.19

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Bump Scala version on 1.0.x branch

### CODE REVIEW

**Comment by raboof** [comment]
is there a particular reason to backport these updates? do they fix any serious bugs?

**Review by raboof — APPROVED** [review]
I'm not opposed, so approving

**Comment by pjfanning** [comment]
I don't think this should have been merged. Generally, we don't backport jar upgrade PRs. Specifically, with this PR, it includes compiler setting changes.

**Comment by He-Pin** [comment]
The new Scala version can help us keep source compatibility when doing backporting,eg:
 [Support binary integer literals using 0b, as in Java ](https://github.com/scala/scala/pull/10656)
[In mixed compilation, allow Java sources to reference MODULE$](https://github.com/scala/scala/pull/10644)

But yes, the future update will need a vote on maillist first.

**Pull request merged**
