### PR TITLE
chore: Fix compiling error in AsSubscriber.java and FromPublisher.java

### PR DESCRIPTION
**Pull request by He-Pin**
Motication:
Fix compiling error.

refs: https://github.com/apache/incubator-pekko/actions/runs/7522637028/job/20474910545

Result:
It compiles now.

### CODE REVIEW

**Review by jxnu-liguobin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
Wait, why wasn't this compiling in the first place? The CI should pickup these things and since the source file is in `java-jdk-9` only this could have been caused by having wrong JDK set or something along those lines?

**Comment by He-Pin** [comment]
@mdedetrich I'm re triggering the nightly build, I think that maybe cause of some dependencies change?

**Comment by mdedetrich** [comment]
@pjfanning Do you have any idea on this?

**Comment by He-Pin** [comment]
Triggered at https://github.com/apache/incubator-pekko/actions/runs/7524512274

**Comment by He-Pin** [comment]
@mdedetrich @pjfanning it's works now.

**Comment by mdedetrich** [comment]
> @mdedetrich @pjfanning it's works now.

I understand that it works now, im questioning why it stopped working in the first place. Our CI should be picking up compilation issues so no PR should have been merged causing this breakage in the first place.

**Comment by mdedetrich** [comment]
> The CI build for PRs mustn't cover ever single line of code. The setup for PRs is a complicated set of subjobs that run in parallel.

If thats the case then we should fix this, at a bare minimum the CI that gets trigged on every PR run should ensure that all code can compile.

**Pull request merged**
