### PR TITLE
perf: Add dedicated collectFirst implementation.

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Use dedicated collectFirst implementation

Result:
Better performance.

### CODE REVIEW

**Review by pjfanning — CHANGES_REQUESTED** [review]
This new class looks a lot like existing Akka based code. Is it truly new? Otherwise, use the Lightbend and Apache header from the original file.

**Comment by He-Pin** [comment]
Yes it's totally new, I changed it from CollectWhile not the origin Collect, why should I? I think every `collectFirst` will implemented this way. And I'm not looking into the code of `Collect` when implement this and CollectWhile.

**Review by pjfanning — APPROVED** [review]
lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

@pjfanning I can also confirm that if you wanted to write this from scratch it would also look like this. While it may look similar to existing akka code, there isn't much you can do about that because generally all of this code has the same style so if you want to write new functionality and keep the existing style it has a very high chance of looking this way.

**Comment by He-Pin** [comment]
Yes, we can ask anyone to write this code, and anyone's code will result in this style.

**Pull request merged**
