### PR TITLE
=str Update FlowMergeAllSpec because the merge order is undefined.

### PR DESCRIPTION
**Pull request by He-Pin**
Was: https://github.com/mdedetrich/akka-apache/pull/6

### CODE REVIEW

**Review by gmethvin — APPROVED** [review]

**Review by mdedetrich — APPROVED** [review]
LGTM

**Review by pjfanning — APPROVED** [review]
LGTM

**Review by nivox — APPROVED** [review]
LGTM

**Comment by pjfanning** [comment]
seems safe to merge now

**Pull request merged**
