### PR TITLE
chore: Fuse In/OutHandler into GraphStageLogic.

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Fuse in and out handle in Split.

Result:
Fewer allocation.

### CODE REVIEW

**Comment by pjfanning** [comment]
@He-Pin is it ok to delay merging this until after the 1.1.0-M1 release?

**Comment by pjfanning** [comment]
@mdedetrich probably looks safe enough - do you think we can merge this for v1.1.0-M1?

**Comment by He-Pin** [comment]
@pjfanning Yes, I think this is safe to be included in 1.1.0-M1.

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
