### PR TITLE
update jar build to include protobuf license

### PR DESCRIPTION
**Pull request by pjfanning**
When adding LICENSE to jars
* most jars don't include protobuf classes - so just include standard Apache license
* for pekko-protobuf, we need the LICENSE that has the section about protobuf and we also need the COPYING.protobuf file

### CODE REVIEW

**Comment by justinmclean** [comment]
HI,

It’s recommend you keep that information in LICENSE see [1]

Kind Regards,
Justin

1. https://infra.apache.org/licensing-howto.html#alv2-dep

**Comment by pjfanning** [comment]
Thanks @justinmclean - the LICENSE gets copied into all the jars. The extra text refers to the COPYING.protobuf file. Should we start adding that to our jars too?

**Comment by justinmclean** [comment]
Yes - see the guiding principle (https://infra.apache.org/licensing-howto.html#guiding). In practice convenience binaries usually have a lot more stuff in them and so will have more things mentioned in LICENSE.

**Comment by pjfanning** [comment]
I raised https://github.com/apache/incubator-pekko/issues/140 for one unresolved issue with this

**Comment by pjfanning** [comment]
@mdedetrich would you be able to review this - it is an ASF requirement to get the licenses correct in our jars

**Comment by mdedetrich** [comment]
Ugh I forgot about this, thanks for raising it.

**Review by jrudolph — APPROVED** [review]
lgtm

**Pull request merged**
