### PR TITLE
=str Deprecate `statefulMapConcat` operator.

### PR DESCRIPTION
**Pull request by He-Pin**
refs https://github.com/apache/incubator-pekko/issues/601

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm, lets not merge until @pjfanning has a look.

**Comment by pjfanning** [comment]
I think it is at least as important to update docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md

**Comment by pjfanning** [comment]
there are also build issues due to the deprecation - see https://github.com/apache/incubator-pekko/actions/runs/6046576863/job/16408388923?pr=608

**Comment by He-Pin** [comment]
There are many usages and need to add the annotation of `nowarn`...

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by pjfanning — CHANGES_REQUESTED** [review]
Could we update the text in docs/src/main/paradox/stream/operators/Source-or-Flow/statefulMapConcat.md to say the function is deprecated and to suggest the alternative approach - ideally with a code snippet for the alternative approach?

**Comment by He-Pin** [comment]
image

@pjfanning is this Ok?

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
