### PR TITLE
Fix key for mdedetrich@apache.org

### PR DESCRIPTION
**Pull request by mdedetrich**
Update incorrect key for mdedetrich@apache.org

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Review by gmethvin — APPROVED** [review]

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
@mdedetrich Make sure not not your key:)

**Comment by pjfanning** [comment]
I checked that the key works for verifying asc files and it does work

**Comment by mdedetrich** [comment]
> I checked that the key works for verifying asc files and it does work

Thanks, merging.

**Pull request merged**
