### PR TITLE
Update Scala to 3.3.3

### PR DESCRIPTION
**Pull request by mdedetrich**
Scala 3.3.2-RC1 just came out so this PR is testing it out to see if the codebase compiles. It will remain in draft until full release of Scala 3.3.2 is out.

### CODE REVIEW

**Comment by He-Pin** [comment]
refs: https://github.com/playframework/playframework/issues/12418

Need to wait for the bug in 3.3.2 to get fixed before merge this

**Comment by mkurz** [comment]
Scala 3.3.2 might even be dropped:
- https://github.com/lampepfl/dotty/issues/19682#issuecomment-1968549966
- https://github.com/scala/scala-lang/pull/1598#issuecomment-1968549355

**Comment by pjfanning** [comment]
3.3.3 is on maven central - https://github.com/lampepfl/dotty/issues/19820#issuecomment-1971111148

Still would be wary of merging this even if it passes CI. I'd prefer to wait a few days to see if there are further issues.

**Comment by mdedetrich** [comment]
> 3.3.3 is on maven central - [lampepfl/dotty#19820 (comment)](https://github.com/lampepfl/dotty/issues/19820#issuecomment-1971111148)
> 
> Still would be wary of merging this even if it passes CI. I'd prefer to wait a few days to see if there are further issues.

We can even wait a week, M1 is in no rush for 1.1.x and 1.1.3-M1 was just released now

**Comment by He-Pin** [comment]
I think you mean 1.0.3-m1

**Comment by mdedetrich** [comment]
> I think you mean 1.0.3-m1, and I think we can backport 3.3.3 to 1.0.x branch once the vote pass.

Yes, fixed

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
Closing in favour of https://github.com/apache/incubator-pekko/pull/1169 which is the same PR

**Pull request closed without merging**
