### PR TITLE
chore: Update scalafmt to 3.7.17

### PR DESCRIPTION
**Pull request by He-Pin**

### CODE REVIEW

**Comment by pjfanning** [comment]
I'm not sure. I won't block this but we use 3.7.11 everywhere else. `scalafmt-native` is tied to the scalafmt version. For me, it best to use the same scalafmt version everywhere. The upgrade is not even useful because the rule changes don't affect us - no code needs reformatting.

**Comment by He-Pin** [comment]
I saw there are some bug fixed.

**Comment by pjfanning** [comment]
the 'bugs' don't seem to affect us

**Comment by He-Pin** [comment]
Let me close this and update when we needed to.

**Pull request closed without merging**
