### PR TITLE
Remove superfluous comma

### PR DESCRIPTION
**Pull request by Philippus**
Witnessed this typo in our logs.

### CODE REVIEW

**Comment by pjfanning** [comment]
@Philippus would you have the log message?

**Comment by Philippus** [comment]
> @Philippus would you have the log message?

relevant part is this: `including myself,, [4] unreachable of [6] members`

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
Merging - Thanks

**Pull request merged**
