### PR TITLE
add sbt-updates plugin

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by mdedetrich** [comment]
What are your thoughts on using scala-steward instead? Its a fully configurable bot that automatically creates PR's with dependency updates that is used throughout Scala OS ecosystem (scala/scala center projects themselves even use it).

**Comment by pjfanning** [comment]
the PR is based on https://github.com/apache/incubator-pekko/issues/56#issuecomment-1329221043 and the following comment with the version upgrades

it would probably be very noisy to have our PR queue filled up by scala steward when there are zero of those PRs that will be accepted right now

with just having the plugin, at least we can check manually to see if there are new updates

**Comment by mdedetrich** [comment]
Was editing the post while you replied, on my point here

> There is also an argument that this should be a global sbt plugin (which you would place in ~/.sbt/1.0/plugins.sbt for example) with the same reasoning as to having global git settings.

How do you feel about adding a section in `CONTRIBUTING.md` on how to add such a global sbt plugin instead? I have also done this in the past with sbt-dependency and similar plugins.

**Comment by pjfanning** [comment]
sure - I guess this is the sort of plugin that works well as a global one

**Pull request closed without merging**
