### PR TITLE
Create KEYS

### PR DESCRIPTION
**Pull request by pjfanning**
* a sample KEYS file
* part of releasing and signing releases
* I have used the key in this file to do ASF releases before
* Whenever anyone else does releases, they should add the public part of their key to this file
* We will link to this file from our download page

### CODE REVIEW

**Comment by mdedetrich** [comment]
FYI on this note, I am going to get my Apache key in the web of trust next week as well as adding it to Apache KEYS file so I can participate in releases

**Comment by justinmclean** [comment]
Hi,

Having it in the web of trust is a nice to have but not a requirement.

Justin

**Comment by pjfanning** [comment]
@mdedetrich @He-Pin Can this be merged? It's useful to have a file to link to in the release docs.

**Review by mdedetrich — APPROVED** [review]
lgtm. I will add mine later

**Pull request merged**
