### PR TITLE
Update blueprint.xml to use pekko namespace

### PR DESCRIPTION
**Pull request by pjfanning**
relates to https://github.com/apache/incubator-pekko/issues/186

`sbt osgi/test` works ok

### CODE REVIEW

**Comment by spangaer** [comment]
I was a bit baffled that you could just change this file without impact. From the looks of it it's only an example and it isn't really parsed anywhere, which is probably why you get away with that. (meaning parsing the config seems to be left to overrides of certain methods of the OSGi classes)

Did stumble on this one in the process
https://github.com/apache/incubator-pekko/blob/main/osgi/src/main/scala/org/apache/pekko/osgi/OsgiActorSystemFactory.scala#L76

**Comment by pjfanning** [comment]
> 
> Did stumble on this one in the process https://github.com/apache/incubator-pekko/blob/main/osgi/src/main/scala/org/apache/pekko/osgi/OsgiActorSystemFactory.scala#L76

I've added a change for that to https://github.com/apache/incubator-pekko/pull/184

There are loads of Akka references still in the code. It's hard to track them all down because we stuck the word Akka into the new license header so almost every file has Akka in it.

**Comment by jrudolph** [comment]
Seems the namespace handler was removed in e98dd13cd68d57d8b8eb188d693600630255de78 so it probably does not matter...

**Comment by pjfanning** [comment]
> Seems the namespace handler was removed in [e98dd13](https://github.com/apache/incubator-pekko/commit/e98dd13cd68d57d8b8eb188d693600630255de78) so it probably does not matter...

Do you think this is ok to merge and if so, could you approve the PR?

**Review by jrudolph — APPROVED** [review]
lgtm (though, we can maybe also just delete the file)

**Comment by pjfanning** [comment]
#201 was merged

**Pull request closed without merging**
