### PR TITLE
WIP: Migrate the classic remoting to Netty 4.

### PR DESCRIPTION
**Pull request by He-Pin**
Based on https://github.com/apache/incubator-pekko/pull/539

For a preview, may not be landing in 1.1.0  if community dediced to remove the classic remoting in 1.1.0.

Personally,+1 for removing classic remoting in 1.2.0 

Will only continue after the the vote done.

### CODE REVIEW

**Comment by pjfanning** [comment]
The discussion on pekko mailing list has not reached a conclusion. I agree with @jrudolph that we are better off removing classic remoting. His point is that it is very hard to test remoting and there is no need to have 2 styles.

So -1 from me on this.

**Review by pjfanning — CHANGES_REQUESTED** [review]
-1 from me - many of us think that we should remove classic remoting and only support artery - or failing that do nothing

**Comment by pjfanning** [comment]
The Pekko community conversation is at https://lists.apache.org/thread/grzp3jw398rtpc6oqfybzxnry2mtyh64

I would just prefer to see consensus there before we consider merging a PR. There's no harm in testing this solution but I'd prefer if it wasn't merged until the community decides on what we want.

**Comment by He-Pin** [comment]
> The Pekko community conversation is at https://lists.apache.org/thread/grzp3jw398rtpc6oqfybzxnry2mtyh64
> 
> I would just prefer to see consensus there before we consider merging a PR. There's no harm in testing this solution but I'd prefer if it wasn't merged until the community decides on what we want.

That's  true, I was testing the idea in this draft.

**Comment by He-Pin** [comment]
@pjfanning and @mdedetrich as The poll result, I think I will close this PR.
https://www.reddit.com/r/scala/comments/160pvne/upgrade_pekkos_classical_transport_to_netty_4_or/

**Comment by mdedetrich** [comment]
Your free to close the PR if you want but as was pointed out in https://www.reddit.com/r/scala/comments/160pvne/comment/jxnuvbf/?utm_source=reddit&utm_medium=web2x&context=3 if we decide to strictly follow semver we may not have a choice here unless we want to ship code with CVE's

**Comment by He-Pin** [comment]
I see the value of keep it and upgrade to Netty 4, but it will need more time to polish too, if it's pr is doomed and will not get merged, then maybe better not put more time on it.

Maybe @pjfanning could share some views too.

**Pull request closed without merging**
