### PR TITLE
Sidestep reproducibility issue

### PR DESCRIPTION
**Pull request by raboof**
Avoids https://github.com/lampepfl/dotty/issues/18248

### CODE REVIEW

**Comment by pjfanning** [comment]
Tentatively, marked as needing a 1.1.0 release. Renaming public methods is unfortunate but I think this generally ok - the change is useful.

**Comment by raboof** [comment]
> Tentatively, marked as needing a 1.1.0 release. Renaming public methods is unfortunate but I think this generally ok - the change is useful.

I don't think this is a public method though: it's an inner method inside the (confusingly named the same) public method. With the change:

```
$ public static void loadExtensions$(org.apache.pekko.actor.typed.internal.ExtensionsImpl);
  public default void loadExtensions();
  public static java.lang.Object $anonfun$loadExtensions$1(org.apache.pekko.actor.typed.internal.ExtensionsImpl, boolean, java.lang.String);
  private void loadExtensionsFor$1(java.lang.String, boolean);
  public static org.apache.pekko.actor.typed.ExtensionId $anonfun$loadExtensions$3(java.lang.Class);
  public static scala.util.Try $anonfun$loadExtensions$2(java.lang.Class);
```

even from the Java perspective `loadExtensionsFor` is private, only `loadExtensions` (unchanged) is public. Mima seems fine with it as well.

**Review by pjfanning — APPROVED** [review]
lgtm - I only looked at the GitHub diff before - now that I see its an inner function, this seems fine

**Comment by pjfanning** [comment]
@raboof would you have time to create a backport PR (branch 1.0.x)?

**Comment by raboof** [comment]
:+1: #739

**Pull request merged**
