### PR TITLE
Upgrade to Scala 2.12.18 and 2.13.11

### PR DESCRIPTION
**Pull request by He-Pin**
refs: https://github.com/apache/incubator-pekko/issues/344

Not for merge , helping test the new scala release.

### CODE REVIEW

**Comment by He-Pin** [comment]
refs: https://github.com/scala/scala/pull/10313

**Comment by mdedetrich** [comment]
Converting to draft until Scala versions are properly released

**Comment by mdedetrich** [comment]
@He-Pin Just to clarify, all of the additional code changes are necessary for the new versions of Scala 2.12/Scala 2.13?

**Comment by He-Pin** [comment]
@mdedetrich Yes, otherwise it won't compile, because the new lint.

**Review by mdedetrich — APPROVED** [review]
Lgtm

**Pull request merged**
