### PR TITLE
Use latest sbt-osgi

### PR DESCRIPTION
**Pull request by mdedetrich**
Resolves: https://github.com/apache/incubator-pekko/issues/757 . See https://github.com/sbt/sbt-osgi/issues/102#issuecomment-1882811884 . I have tested that this works with pekko-http using

```
sbt -Dpekko.build.pekko.version=1.1.0-M0-SNAPSHOT "++ 2.12.18" Test/compile
sbt -Dpekko.http.parallelExecution=false -Dpekko.test.timefactor=2 -Dpekko.build.pekko.version=1.1.0-M0-SNAPSHOT "++ 2.12.18" mimaReportBinaryIssues test
```

where `1.1.0-M0-SNAPSHOT` is a version I manually set for this PR.

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
Ill go ahead and merge this so we can iron out any regressions

**Comment by mdedetrich** [comment]
I can confirm that this is working correctly, the latest pekko-http nightly builds passed without issues (see https://github.com/apache/incubator-pekko-http/actions/runs/7469468687)

**Pull request merged**
