### PR TITLE
protect 1.0.x branch

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by mdedetrich** [comment]
Note that before you protect 1.0.x branch you need to add a commit to update https://github.com/apache/incubator-pekko/blob/main/.github/workflows/format.yml#L24 to arguments: '--list --mode diff-ref=origin/1.0.x' (if you want I can do this).

**Comment by pjfanning** [comment]
> Note that before you protect 1.0.x branch you need to add a commit to update https://github.com/apache/incubator-pekko/blob/main/.github/workflows/format.yml#L24 to arguments: `--list --mode diff-ref=origin/1.0.x` (if you want I can do this).

should we genericise the job using one of the answers in this (maybe the 280 vote one)?

 https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions

**Comment by mdedetrich** [comment]
> should we genericise the job using one of the answers in this (maybe the 280 vote one)?
> 
> https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions

Sure go ahead, lets try it before merging this PR

**Comment by pjfanning** [comment]
> > should we genericise the job using one of the answers in this (maybe the 280 vote one)?
> > https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
> 
> Sure go ahead, lets try it before merging this PR

I thought about it again and I suspect that we could end up getting PRs to validate against the PR branch as opposed to the target branch. Possibly just easier to hardcode the branch.

**Review by He-Pin — APPROVED** [review]
Lgtm

**Pull request merged**
