### PR TITLE
Delete PrettyByteString.scala

### PR DESCRIPTION
**Pull request by pjfanning**
Doesn't seem to be used.

And any comment that has 'based on' and a link to code is going to cause us problems in code reviews. Licensing and other concerns.

### CODE REVIEW

**Comment by mdedetrich** [comment]
Did you check that this isn't used in all of Pekkos modules or just this one?

**Comment by pjfanning** [comment]
I found one in a test in pekko-http-core

https://github.com/search?q=repo%3Aapache%2Fincubator-pekko-http+PrettyByteString&type=code

Looks fixable - it should be feasible to modify the test.

I won't do anything for next few days. I've sent a mesage to @justinmclean about this class and the fact that @jrudolph was a Lightbend staff member - so there is a string argument that we don't need special license treatment for this.

**Comment by He-Pin** [comment]
It may be used in http or debugging i think

**Comment by jrudolph** [comment]
Yes, can go. In this case, "based" meant basically upstreaming some debugging code from akka-http to akka. The http module has similar/same code in `LogByteStringTools.scala` which can be used in the tests instead. I'll add a PR for pekko-http.

**Comment by jrudolph** [comment]
https://github.com/apache/incubator-pekko-http/pull/191

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko-http/pull/191 is merged so this is now safe to merge.

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
