### PR TITLE
Upgrade sbt-pull-request-validator

### PR DESCRIPTION
**Pull request by mkurz**
@mdedetrich knows

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
Lgtm

**Review by pjfanning — APPROVED** [review]
lgtm - pending CI (the link validator issue is not caused by this change)

**Comment by He-Pin** [comment]
The release note : https://github.com/sbt/sbt-pull-request-validator/releases/tag/v2.0.0

**Comment by mkurz** [comment]
can be merged I guess.

**Comment by pjfanning** [comment]
I'll back port this to the 1.0.x branch later

**Pull request merged**
