### PR TITLE
remove check for old implementation of Akka Discovery

### PR DESCRIPTION
**Pull request by pjfanning**
* pekko-discovery will not work directly with any implementation of Akka Discovery.
* we've already messed up this test with a global replace that affects the classname

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
Looks good to me.

On a somewhat related note, there is an argument that we should implement similar checks in pekko but actually for any akka artifacts that happen to be on the classpath (i.e. to prevent mixing akka and pekko artifats).

Should I make an issue for this?

**Comment by pjfanning** [comment]
> Looks good to me.
> 
> On a somewhat related note, there is an argument that we should implement similar checks in pekko but actually for any akka artifacts that happen to be on the classpath (i.e. to prevent mixing akka and pekko artifacts).
> 
> Should I make an issue for this?

Worth tracking an issue but generally, having main Akka libs and Pekko libs on same classpath should be ok. This issue is more about Pekko checking about using an even older Discovery mechanism pre-dating akka-discovery joining the core of Akka.

**Comment by mdedetrich** [comment]
> Worth tracking an issue but generally, having main Akka libs and Pekko libs on same classpath should be ok. 

Yes but usually it would indicate that you may have done something wrong

**Comment by pjfanning** [comment]
> > Worth tracking an issue but generally, having main Akka libs and Pekko libs on same classpath should be ok.
> 
> Yes but usually it would indicate that you may have done something wrong

Sure - log an issue and it can be discussed. I would prefer to start by logging a warning. But if experience teaches us that having both sets of classes leads to issues, we can make it a failure condition.

**Pull request merged**
