### PR TITLE
chore: Add Flow#flattenMerge operator.

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Add this Scala dsl for make it more friendly and easy to use in scaldsl.

also we can see this in Kotlin's flow and ZIO.
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/flatten-merge.html

### CODE REVIEW

**Review by zhongwm — APPROVED** [review]
L. G.

**Review by jxnu-liguobin — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
no docs?

**Comment by He-Pin** [comment]
I thought this operator was too natively for Scala developers, but I can add one.

**Comment by pjfanning** [comment]
it's worth some basic mention in our paradox docs

**Comment by He-Pin** [comment]
I will update with a doc after lunch, thanks for the review.

**Comment by He-Pin** [comment]
@pjfanning I have added the document.

**Pull request merged**
