### PR TITLE
Update the javafmt version and reformat

### PR DESCRIPTION
**Pull request by He-Pin**
I always need to do manual revert after running a local test, so I think it better to reformat it.

### CODE REVIEW

**Comment by mdedetrich** [comment]
@He-Pin The code format check is still failing, did you format all files?

**Comment by He-Pin** [comment]
@mdedetrich Maybe I'm using windows?

**Comment by mdedetrich** [comment]
@He-Pin Should I recreate the PR myself? I will give you credit via `Co-Authored-By`?

**Comment by He-Pin** [comment]
@mdedetrich Do it, thanks.

**Pull request closed without merging**
