### PR TITLE
Remove sbtx usage

### PR DESCRIPTION
**Pull request by jchapuis**
Fix for #59 

Replace by prior copy of `.jvmopts-ci` into `.jvmopts` which is the file sbt natively supports

Naive approach, just trying to help, not sure if that's what you expected? 😄  It seems sbt doesn't support a custom filename for jvm opts

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm

**Review by mdedetrich — CHANGES_REQUESTED** [review]
Is there a reason why we are doing a `cp .jvmopts-ci .jvmopts` instead of just renaming the `.jvmopts-ci` file to `.jvmopts`?

I just did a quick grep and `.jvmopts-ci` seems to only be used by sbtx in ci so it seems to be pretty safe?

**Comment by jchapuis** [comment]
@mdedetrich yes indeed, we could rename, that's the alternative. However, naturally, this means these options would also be picked up when starting sbt locally, which is maybe not what we want 🤔 ? 
Do we actually know if these options are necessary at all? some of them might no longer be relevant, e.g. `UseCompressedOops` seems to be a default nowadays

**Comment by mdedetrich** [comment]
> yes indeed, we could rename, that's the alternative. However, naturally, this means these options would also be picked up when starting sbt locally, which is maybe not what we want 🤔 ?

So the underlying point of the issue and this PR is that `sbtx` is actually not used in any distribution if you install sbt the standard way. A lot of functionality over time has moved from `sbtx` to `sbt` and today there is no reason to use sbt. This is why @SethTisue was annoyed with `setup-scala` aliasing `sbt` to `sbtx` because its misleading.

The tl;dr is that nowadays if you have sbt on Linux/Mac/Windows its just using standard sbt (not `sbtx`) and its ignoring those cli options anyways

> Do we actually know if these options are necessary at all? some of them might no longer be relevant, e.g. UseCompressedOops seems to be a default nowadays

That is a fair point but I would fix this in a separate PR just to make things clear.

**Comment by jchapuis** [comment]
@mdedetrich thanks yes I think I understand the context of this issue. My only concern was that by renaming `.jvmopts-ci` to `.jvmopts` in the repo, when you start `sbt` (not `sbtx`, just the standard `sbt`), it will actually pickup these options for your local development session (which could be counter-intuitive, as it's "hidden"). Compared to sbtx, it just doesn't allow specifying the file - but the functionality is there with the hardcoded name.  

If that's acceptable, for sure we can rename it and ditch the preliminary copying step. 

But I was guessing here that it had been kept separate to make it clear that these options were only relevant for the CI, and so I thought it relevant to keep this intention 🤷

**Review by mdedetrich — APPROVED** [review]
LGTM, questions answered

**Pull request merged**
