### PR TITLE
Remove hard-coded scalafmt version

### PR DESCRIPTION
**Pull request by mzuehlke**
Since `scalafmt-native-action v3` the scalafmt version will be picked up from the `.scalafmt.conf` file.

see: https://github.com/jrouly/scalafmt-native-action/releases/tag/v3

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by raboof — APPROVED** [review]
that looks very familiar ;)

**Comment by mdedetrich** [comment]
So it seems like I am unable to merge this due to a chicken and egg problem because the old status check isn't passing even though its being changed in this PR.

@mzuehlke We may need to separate the PR's, can you undo the change where the scalafmt version is removed (but keep the bump to scalafmt-native-action)  so the PR can pass the status check and then make another PR which just removes the version?

**Comment by raboof** [comment]
> So it seems like I am unable to merge this due to a chicken and egg problem because the old status check isn't passing even though its being changed in this PR.
> 
> @mzuehlke We may need to separate the PR's, can you undo the change where the scalafmt version is removed (but keep the bump to scalafmt-native-action) so the PR can pass the status check and then make another PR which just removes the version?

I don't think that's the issue, https://github.com/apache/incubator-pekko/actions/runs/7395512012 suggests the issue is that this tag is simply not whitelisted yet:

```
jrouly/scalafmt-native-action@v3 is not allowed to be used in apache/incubator-pekko. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, gaurav-nelson/github-action-markdown-link...
```

**Comment by pjfanning** [comment]
@mdedetrich @raboof I'll raise an INFRA issue.
@mzuehlke this PR doesn't need to change. When we get jrouly/scalafmt-native-action@v3 approved, we can rerun the CI ourselves.

**Comment by pjfanning** [comment]
https://issues.apache.org/jira/browse/INFRA-24804 raised

**Review by pjfanning — APPROVED** [review]
lgtm - INFRA isssue is resolved - this can be merged when the CI run completes

**Comment by mzuehlke** [comment]
thanks for handling the INFRA issue @pjfanning

**Pull request merged**
