### PR TITLE
=sbt Update Netty4 version to 4.1.97.final.

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Update Netty 4 to latest version.

### CODE REVIEW

**Comment by He-Pin** [comment]
I checked the release note and the failure is unrelated.

**Comment by He-Pin** [comment]
> lgtm
> 
> I think https://lists.apache.org/thread/878y7f5hrf0o7h7z8ct2kfgs28x83xmv is a better solution.

Yes，@mdedetrich said apache prefer thier own runner？

**Comment by He-Pin** [comment]
Let me close this and let the steward to handle this.

**Comment by pjfanning** [comment]
I am not aware of any ASF rules on Scala Steward. There are some ASF projects in https://github.com/VirtusLab/scala-steward-repos/blob/main/repos-github.md

**Pull request closed without merging**
