### PR TITLE
remove publish-docs job

### PR DESCRIPTION
**Pull request by pjfanning**
* Relates to https://github.com/apache/incubator-pekko/issues/99
* replaced by https://github.com/apache/incubator-pekko-site for the time being

### CODE REVIEW

**Comment by pjfanning** [comment]
@mdedetrich would you be able to review this? The failing CI builds are creating a fair amount of noise.

**Comment by mdedetrich** [comment]
Also is https://github.com/apache/incubator-pekko/actions/runs/4005748253/jobs/6876480922 related?

**Comment by pjfanning** [comment]
yes - all commits to main are marked as red `x` because of this failing job - see https://github.com/apache/incubator-pekko/commits/main

**Review by mdedetrich — APPROVED** [review]
So this is failing because its using sbt-rsync which is probably pointing to the wrong location, it actually should be replaced with something like the existing nightlies publish at https://github.com/apache/incubator-pekko/blob/main/.github/actions/sync-nightlies/action.yml.

I can look into this, I would however recommended not spending too much time trying to fix this with a separate repo because the fix should be quite trivial.

lgtm, okay for now.

**Comment by pjfanning** [comment]
I'm not aware of a rsync doc publishing solution supported by ASF Infra team. The site repo uses what I know to be supported but it would be great to automate something.

**Comment by mdedetrich** [comment]
> I'm not aware of a rsync doc publishing solution supported by ASF Infra team. The site repo uses what I know to be supported but it would be great to automate something.

I thought that publishing docs essentially meant pushing the docs (i.e. generated `*.html`/`*.js` etc etc) files over rsync to some directly which is then served as a webpage?

**Comment by pjfanning** [comment]
> > I'm not aware of a rsync doc publishing solution supported by ASF Infra team. The site repo uses what I know to be supported but it would be great to automate something.
> 
> I thought that publishing docs essentially meant pushing the docs (i.e. generated `*.html`/`*.js` etc etc) files over rsync to some directly which is then served as a webpage?

I have not found any support for this. So far, all I've been told about is what https://github.com/apache/incubator-pekko-site/blob/main/.asf.yaml does (publish and staging sections). Documented in https://cwiki.apache.org/confluence/display/FLUME/How+to+Release#HowtoRelease-Updatethewebsite

**Comment by mdedetrich** [comment]
> https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-WebsitedeploymentserviceforGitrepositories

So I had just had a quick glimpse into this and it does appear for at least the main website, a separate repo makes sense. However for doc generation (javadoc/scaladoc/paradox) this I think can be hosted elsewhere (even hypothetically in nightlies, I have seen projects putting documentation there) since they can serve `index.html` files and rsync is handy for this because you can specify a single folder containing the docs (which is pretty much how every mainstream language's doc generation works).

The main website can then just point to the docs that are hosted elsewhere

**Pull request merged**
