### PR TITLE
=build Update to sbt 1.9.0-RC3

### PR DESCRIPTION
**Pull request by He-Pin**
Update to sbt 1.9.0-RC3

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
@He-Pin Do you want to do this change to the other pekko modules?

**Comment by He-Pin** [comment]
> @He-Pin Do you want to do this change to the other pekko modules?

I can do a review, i'm not aside my pc.

**Comment by mkurz** [comment]
1.9.0 final released already

**Comment by mdedetrich** [comment]
Apologies this was the wrong PR, was talking about newly released Scala versions

**Pull request merged**
