### PR TITLE
remove unused log4j dependency

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
@pjfanning Shall we backport this to `1.0.x`?

**Comment by He-Pin** [comment]
It's never been used, so it's safe.

**Comment by mdedetrich** [comment]
> As @He-Pin says, it isn't used so it doesn't cause any harm to leave it. It is just useful to tidy up the `main` branch so that we don't have it indefinitely.

Oh by isn't used I thought you meant it was part of the dependency tree but not actually needed, but instead its just a standalone variable (was looking at the PR on my phone so didn't really notice).

All good then

**Pull request merged**
