### PR TITLE
=build Use zulu in nightly build to test jdk21.

### PR DESCRIPTION
**Pull request by He-Pin**
There is no jdk21 temurin release for now, so I have to switch to zulu or oracle :(

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm - we can switch back to temurin later (when they have a jdk 21 release)

**Comment by He-Pin** [comment]
@pjfanning Is there any special vaue to chose `temurin` instead of zulu or oracle?

**Comment by mdedetrich** [comment]
> @pjfanning Is there any special vaue to chose `temurin` instead of zulu or oracle?

Temurin is built from official OpenJDK sources, zulu/oracle are not

**Comment by mkurz** [comment]
fyi, we had the same problem in Play. So I created my own jvm index that contains the latest Java Temurin ea builds: https://github.com/mkurz/jvm-index/blob/adoptium_temurin_eaps/index.json
Hopefully setup-action merges my PR for for the `--jvm-index` at some point: https://github.com/coursier/setup-action/pull/465 
Meanwhile I forked the action to be able to make use of the flag: https://github.com/playframework/.github/commit/631bb350b180702db35343bf9d131fb683105a59 and  https://github.com/playframework/.github/commit/216eb922fd4b5c5ceb7e570996f3140f530ed877
We can now sucessfully test Temurin ea builds: https://github.com/playframework/playframework/pull/11925/files#diff-063ca77e012f959eba648db60e6868875fd1e70e5f5ac081193d848f8d61ef32R86

**Comment by He-Pin** [comment]
@mkurz Where to ask they to do a 21 release?

**Comment by mkurz** [comment]
@He-Pin 
First Adoptium needs to provide the Temurin 21 builds, this usually takes a couple of days:
https://github.com/adoptium/adoptium/issues/248
So we just have to wait here.
Then the coursier jvm-index needs to fetch that new release once it's published, so we need to adjust this line to include 21: https://github.com/coursier/jvm-index/blob/master/src/Temurin.scala#L5
Then someone needs to run that tool, like described in the README of https://github.com/coursier/jvm-index/ so the `index.json`  in that repository gets updated.

**Pull request merged**
