### PR TITLE
Document testQuick in welcome screen

### PR DESCRIPTION
**Pull request by mdedetrich**
Useful in both diagnosing and dealing with flaky tests

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
any chance that some of these useful commands could be added to the README.md (section about building from source)

**Comment by mdedetrich** [comment]
Sure I will add in `testQuick` briefly (otherwise just duplicating info) but from what I can tell most of the stuff in README.md (i.e. https://github.com/apache/incubator-pekko/blob/0bb2e8668b2a77fe9b57a5ab61a96d9c6e70317f/README.md#L24-L47) should probably sit in `CONTRIBUTING.md`

**Comment by pjfanning** [comment]
> So the discussion on what stuff sits in `README.md` vs `CONTRIBUTING.md` can be made elsewhere, just updated PR to add `sbt testQuick` in `README.md`

We have to keep the README stuff for a few days anyway because it is linked in the vote thread email.

I still think we need 2 docs - the detailed one for people who want to get super involved with Pekko contributing and one for more casual users who might just want to do some cursory checks on the source distribution.

**Pull request merged**
